# Generated by Django 6.0.3 on 2026-03-03 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('area_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('is_heavy', models.BooleanField(default=False)),
                ('tools_required', models.TextField(blank=True)),
                ('specialization', models.CharField(choices=[('none', 'None'), ('class', 'Class Based'), ('dorm', 'Dorm Based'), ('form', 'Form Based'), ('subject', 'Subject Based')], default='none', max_length=20)),
                ('specific_subject', models.CharField(blank=True, max_length=100)),
                ('students_required', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_areas', to='schools.school')),
                ('specific_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.class')),
                ('specific_dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.dorm')),
                ('specific_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.form')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('school', 'label')},
            },
        ),
        migrations.CreateModel(
            name='DutyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_history', to='duties.dutyarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_history', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_history', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_history', to='schools.term')),
            ],
        ),
        migrations.CreateModel(
            name='DutySwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('from_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='duties.dutyarea')),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='students.student')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='schools.term')),
                ('to_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='duties.dutyarea')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.PositiveIntegerField(default=1)),
                ('method', models.CharField(choices=[('auto', 'Auto Assigned'), ('manual', 'Manually Assigned'), ('swap', 'Swap')], default='auto', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('duty_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duties.dutyarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.term')),
            ],
            options={
                'ordering': ['duty_area__label', 'student__last_name'],
                'unique_together': {('term', 'student', 'rotation')},
            },
        ),
    ]
