# Generated by Django 6.0.3 on 2026-03-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_created_at_school_registered_at_school_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_done', models.BooleanField(default=False)),
                ('forms_done', models.BooleanField(default=False)),
                ('classes_done', models.BooleanField(default=False)),
                ('dorms_done', models.BooleanField(default=False)),
                ('duty_areas_done', models.BooleanField(default=False)),
                ('students_done', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wizard', to='schools.school')),
            ],
        ),
    ]
